import assert from 'node:assert/strict';
import { generateKeyPairSync, randomBytes, randomUUID } from 'node:crypto';
import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import test from 'node:test';
import pg from 'pg';
import { POSTGRES_17_IMAGE, assertLocalTestEnvironment, psql, startPostgresContainer, stopAndRemoveContainer } from '../support/foundation-docker.js';
import { AUTHZ_ID, SUBJECTS, installStaffFixture, staffPoolOptions } from '../support/staff-authorization.js';
import { CJ_ID, CJ_SUBJECTS, clientJobFixtureSql } from '../support/client-job-workflows.js';
import { withStaffTransaction } from '../../src/lib/staff-authorization.js';
import { telegramConnectionStatus, telegramConnectionAction, telegramConnectorOperation } from '../../src/lib/telegram-connection-operations.js';
const migrationsDir = fileURLToPath(new URL('../../supabase/migrations/', import.meta.url));
const migration = '20261002140000_telegram_connection.sql';
const migrations = readdirSync(migrationsDir).filter(file => file >= '20260922090000_foundation_roles.sql' && file <= migration && file.endsWith('.sql')).sort();
const identity = (subject) => ({ provider: 'google', issuer: 'https://accounts.google.com', subject });
const { ORG_A, ORG_B } = AUTHZ_ID;
const key = () => generateKeyPairSync('rsa', { modulusLength: 2048 }).publicKey.export({ format: 'der', type: 'spki' }).toString('base64');

test('private Telegram QR connection, ciphertext handoff and generation fencing', async t => {
    assertLocalTestEnvironment();
    const container = await startPostgresContainer('pgtelegramconnect', POSTGRES_17_IMAGE, { publish: true });
    let pool; let workerPool;
    t.after(async () => { await Promise.all([pool?.end(), workerPool?.end()]); await stopAndRemoveContainer(container); });
    for (const file of migrations) psql(container, readFileSync(join(migrationsDir, file), 'utf8'));
    const password = installStaffFixture(container); psql(container, clientJobFixtureSql);
    psql(container, `insert into app.role_permissions(organization_id,role_id,permission_key) values('${ORG_B}','${CJ_ID.ROLE_B_RECRUITER}','candidates.write');`);
    pool = new pg.Pool(staffPoolOptions(container, password, 4));
    const workerPassword = randomUUID();
    psql(container, `create role connector_test login noinherit nosuperuser nocreatedb nocreaterole nobypassrls password '${workerPassword}'; grant app_telegram_worker to connector_test;`);
    workerPool = new pg.Pool({ ...staffPoolOptions(container, workerPassword, 3), user: 'connector_test' });
    const owner = identity(CJ_SUBJECTS.ADMIN); const other = identity(CJ_SUBJECTS.RECRUITER);
    const staff = (sql, args = [], who = owner, org = ORG_B) => withStaffTransaction(pool, who, org, ['candidates.read', 'candidates.write'], async ({ client }) => (await client.query(sql, args)).rows[0]?.result);
    const scalar = sql => psql(container, sql).trim();
    const token = randomBytes(48).toString('base64url');
    const token2 = randomBytes(48).toString('base64url');
    const worker = await staff('select app.telegram_register_worker_v1($1,$2) as result', ['Connector', token]);
    const worker2 = await staff('select app.telegram_register_worker_v1($1,$2) as result', ['Other connector', token2], other);
    const publicKeySpki = key();
    const call = (action, body = {}, credential = token) => telegramConnectorOperation(workerPool, credential, action, body);
    const status = (who = owner, org = ORG_B) => telegramConnectionStatus(pool, who, org);
    const action = (input, who = owner, org = ORG_B) => telegramConnectionAction(pool, who, org, input);
    let connection; let lease;
    const report = (input, task = lease, credential = token) => call('update', { connectionId: task.id, generation: task.generation, leaseToken: task.leaseToken, ...input }, credential);
    const profile = { telegramUserId: '123456789012345', username: 'synthetic_user', displayName: 'Synthetic Person' };

    await t.test('runtime role has only function access and owner-scoped worker discovery', async () => {
        const c = await workerPool.connect();
        try {
            await c.query('set role app_telegram_worker');
            const { rows: [role] } = await c.query('select current_user as role, rolsuper, rolbypassrls from pg_roles where rolname=current_user');
            assert.deepEqual(role, { role: 'app_telegram_worker', rolsuper: false, rolbypassrls: false });
            await assert.rejects(c.query('select * from app.telegram_connections'), { code: '42501' });
            await assert.rejects(c.query('select app.telegram_connection_status_v1()'), { code: '42501' });
            await assert.rejects(c.query('select app.telegram_worker_context_v1($1)', [token]), { code: '42501' });
        } finally { c.release(); }
        await call('heartbeat', { publicKeySpki });
        await call('heartbeat', { publicKeySpki: key() }, token2);
        assert.deepEqual((await status()).workers.map(w => w.id), [worker.id]);
        assert.deepEqual((await status(other)).workers.map(w => w.id), [worker2.id]);
        assert.deepEqual((await status(identity(SUBJECTS.ADMIN2), ORG_A)).workers, []);
        await assert.rejects(action({ action: 'connect', workerId: worker2.id }), { code: '40001' });
        await assert.rejects(status(identity(CJ_SUBJECTS.VIEWER)), { code: 'FORBIDDEN' });
    });
    await t.test('unclaimed first connection cancellation is immediate without claiming remote logout', async () => {
        const started = (await action({ action: 'connect', workerId: worker.id })).connection;
        const cancelled = (await action({ action: 'disconnect', connectionId: started.id, generation: started.generation })).connection;
        assert.equal(cancelled.status, 'disconnected'); assert.equal(cancelled.cancelledBeforeStart, true);
        assert.equal(await call('claim'), null);
    });
    await t.test('concurrent start is idempotent and keys are pinned until disconnect', async () => {
        const started = await Promise.all([action({ action: 'connect', workerId: worker.id }), action({ action: 'connect', workerId: worker.id })]);
        connection = started[0].connection;
        assert.equal(started[1].connection.id, connection.id); assert.equal(started[1].connection.generation, connection.generation);
        await assert.rejects(call('heartbeat', { publicKeySpki: key() }), { code: '40001' });
        assert.equal((await status(other)).connection, null);
        lease = await call('claim');
        assert.equal((await call('claim')).leaseToken, lease.leaseToken);
        assert.equal(await call('claim', {}, token2), null);
        await assert.rejects(report({ status: 'failed', errorCode: 'AUTH_FAILED' }, lease, token2), { code: '40001' });
    });
    await t.test('QR reporting only exposes valid private challenge, then encrypted submission exact acknowledgement', async () => {
        await report({ status: 'qr_pending', challengeId: lease.challengeId, qrLoginUrl: 'tg://login?token=synthetic123', qrExpiresAt: new Date(Date.now() + 45000).toISOString() });
        connection = (await status()).connection;
        assert.equal(connection.qrLoginUrl, 'tg://login?token=synthetic123');
        assert.ok(!JSON.stringify(connection).includes('leaseToken'));
        await report({ status: 'awaiting_password', challengeId: lease.challengeId, passwordHint: 'Synthetic hint' });
        const ciphertext = randomBytes(256).toString('base64');
        const passwordAction = { action: 'password', connectionId: lease.id, generation: lease.generation, challengeId: lease.challengeId, ciphertext };
        await assert.rejects(action(passwordAction, other), { code: '40001' });
        await action(passwordAction);
        assert.equal((await status()).connection.passwordPending, true);
        assert.ok(!JSON.stringify(await status()).includes(ciphertext));
        const submitted = await call('claim');
        assert.equal(submitted.passwordCiphertext, ciphertext); assert.ok(submitted.passwordSubmissionId);
        await report({ status: 'awaiting_password', challengeId: lease.challengeId });
        assert.equal((await call('claim')).passwordCiphertext, ciphertext, 'delayed initial report cannot erase submission');
        await report({ status: 'awaiting_password', challengeId: lease.challengeId, passwordSubmissionId: submitted.passwordSubmissionId, errorCode: 'PASSWORD_INVALID' });
        assert.equal((await call('claim')).passwordCiphertext, null);
        await action({ ...passwordAction, ciphertext: randomBytes(256).toString('base64') });
        const newerSubmission = await call('claim');
        await report({ status: 'awaiting_password', challengeId: lease.challengeId, passwordSubmissionId: submitted.passwordSubmissionId, errorCode: 'PASSWORD_INVALID' });
        assert.equal((await call('claim')).passwordSubmissionId, newerSubmission.passwordSubmissionId, 'lost-ACK replay must not erase newer submission');
        await assert.rejects(report({ status: 'awaiting_password', challengeId: lease.challengeId, passwordSubmissionId: randomUUID() }), { code: '40001' });
        await report({ status: 'connected', profile });
        connection = (await status()).connection;
        assert.equal(connection.status, 'connected'); assert.deepEqual(connection.profile, profile); assert.equal(connection.passwordPending, false);
        await report({ status: 'connected', profile });
        await assert.rejects(report({ status: 'awaiting_password', challengeId: lease.challengeId }), { code: '40001' });
    });
    await t.test('disconnect fences old lease immediately and waits for Mac acknowledgement', async () => {
        const before = lease;
        connection = (await action({ action: 'disconnect', connectionId: lease.id, generation: lease.generation })).connection;
        assert.equal(connection.status, 'disconnecting'); assert.equal(connection.generation, before.generation + 1); assert.equal(connection.profile, null);
        assert.equal((await action({ action: 'disconnect', connectionId: lease.id, generation: before.generation })).connection.generation, connection.generation);
        await assert.rejects(report({ status: 'connected', profile }, before), { code: '40001' });
        lease = await call('claim');
        await report({ status: 'disconnecting', errorCode: 'LOGOUT_FAILED' });
        assert.equal((await status()).connection.status, 'disconnecting');
        await report({ status: 'disconnected' });
        await report({ status: 'disconnected' }); // Lost acknowledgement replay is harmless.
        assert.equal((await status()).connection.status, 'disconnected'); assert.equal(await call('claim'), null);
        await call('heartbeat', { publicKeySpki: key() });
    });
    await t.test('expiry and expired leases prevent stale login completion and clear ciphertext', async () => {
        connection = (await action({ action: 'connect', workerId: worker.id })).connection;
        lease = await call('claim');
        await report({ status: 'awaiting_password', challengeId: lease.challengeId });
        await action({ action: 'password', connectionId: lease.id, generation: lease.generation, challengeId: lease.challengeId, ciphertext: randomBytes(256).toString('base64') });
        psql(container, `update app.telegram_connections set password_expires_at=now()-interval '1 second' where id='${lease.id}'`);
        assert.equal((await call('claim')).passwordCiphertext, null);
        psql(container, `update app.telegram_connections set lease_expires_at=now()-interval '1 second' where id='${lease.id}'`);
        await assert.rejects(report({ status: 'connected', profile }), { code: '40001' });
        const fresh = await call('claim'); assert.notEqual(fresh.leaseToken, lease.leaseToken);
        psql(container, `update app.telegram_connections set auth_expires_at=now()-interval '1 second' where id='${lease.id}'`);
        connection = (await status()).connection;
        assert.equal(connection.status, 'failed'); assert.equal(connection.errorCode, 'LOGIN_EXPIRED'); assert.equal(connection.generation, lease.generation + 1);
        await assert.rejects(report({ status: 'connected', profile }, fresh), { code: '40001' });
        const restarted = (await action({ action: 'connect', workerId: worker.id })).connection;
        const retryCancel = (await action({ action: 'disconnect', connectionId: restarted.id, generation: restarted.generation })).connection;
        assert.equal(retryCancel.status, 'disconnecting'); assert.equal(retryCancel.cancelledBeforeStart, false, 'failed/restart must preserve prior lease history');
        assert.equal((await call('claim')).status, 'disconnecting');
        assert.equal(scalar(`select password_ciphertext is null and qr_login_url is null from app.telegram_connections where id='${lease.id}'`), 't');
    });
    await t.test('revocation and membership loss deny future connector calls', async () => {
        await staff('select app.telegram_revoke_worker_v1($1) as result', [worker.id]);
        await assert.rejects(call('claim'), { code: '42501' });
        await assert.rejects(call('heartbeat', { publicKeySpki }), { code: '42501' });
        assert.deepEqual((await status()).workers, []);
        psql(container, `update app.organization_memberships set status='revoked',revoked_at=now() where organization_id='${ORG_B}' and user_id=(select owner_user_id from app.telegram_workers where id='${worker2.id}')`);
        await assert.rejects(call('claim', {}, token2), { code: '42501' });
    });
});
