begin;

create table if not exists public.applicants (
    id bigint generated by default as identity primary key,
    full_name text not null,
    email text not null,
    cv_url text not null,
    ref_id text not null,
    status text not null default 'pending',
    created_at timestamptz not null default now()
);

alter table public.applicants
    add column if not exists job_id text,
    add column if not exists job_title text,
    add column if not exists professional_url text,
    add column if not exists technical_achievement text;

alter table public.applicants enable row level security;

create index if not exists applicants_job_id_idx on public.applicants (job_id);
create index if not exists applicants_created_at_idx on public.applicants (created_at desc);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'cv-submissions',
    'cv-submissions',
    false,
    4 * 1024 * 1024,
    array[
        'application/pdf',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
    ]
)
on conflict (id) do nothing;

commit;
